### PR TITLE
Fix compile issues under Mac OS X, some warnings, and uncrustify.

### PR DESCRIPTION
**Pull request by mgarlanger**

### CODE REVIEW

**Comment by mgarlanger** [comment]
Most of the int -> unsigned long are due to `strtoul()` calls. The other option would be to change that to strtol() 

On the ssize_t, the warning said that the return type was 'ssize_t, aka long', so I had used long, I'll change that to ssize_t

I'll take a look at the changes in HostFileBdos. As for the difference, there were a few places I did a small change to trigger the reformat, specifically class initializers. If the first one is on the same line, it will then line the rest up with that one. Since most(or hopefully) all the other classes are that way, I made those changes to those classes. Otherwise if the first one was on the next line, it would only indent them all 4 spaces.  Was there other changes you saw besides that one?

**Comment by durgadas311** [comment]
I went through the strtoul stuff and will submit a proposed fix. I'd rather keep the ripples to a minimum, and only change the actual usage of strtoul. Oddly, GCC -Wall does not complain about strtoul. I wonder why. Supposedly there is no more to warn about after -Wall. I was using strtoul because I, mistakenly, thought it prevented "-" but I now find out that, at least on Linux, it still parses negative numbers but just casts them to unsigned. I found other warnings with -Wall and will include those. 

As I recall, OSX compiler warns about more than GCC default, but much less than GCC -Wall. Exception being strtoul, it seems.

**Comment by mgarlanger** [comment]
I see that uncrustify removed some spaces from the table in HostFileBdos, but everything still lines up and it didn't move anything to new lines.

**Comment by durgadas311** [comment]
The problem with the table is that uncrustify and spread out the items and wrapped to new lines, so it looses the organization around the BDOS Function numbers and the comments no longer help get one oriented as to which entry is for which BDOS function.

**Comment by mgarlanger** [comment]
Ok, I've reverted all the changes I made just for warnings. This PR has only the changes need to compile (updated xcode project file), compile errors under Mac OS X, and a run of uncrustify.

**Comment by mgarlanger** [comment]
I think what you are seeing, is due to github wrapping lines in the diff, that are not wrapped in the actual changes. Make sure your browser is wide enough to see the diff without it wrapping. You can also click on the 'View' button to see the whole file. Let me know if you still see any issues with the table.

**Comment by durgadas311** [comment]
When I edit the file HostFileBdos.cpp I see the table expanded and wrapped, I was not looking at github diffs. I fixed the table in the last edit, but uncrustify blew it up again.

Sent from my Samsung Galaxy Tab®|PRO

-------- Original message --------

**Pull request merged**
